require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"

require "user.autocommands"
require "user.autopairs"
require "user.bufferline"
require "user.cmp"
require "user.comment"
require "user.dap.init"
require "user.gitsigns"
require "user.illuminate"
require "user.indentline"
require "user.impatient"
require "user.lualine"
require "user.nvim-tree"
require "user.telescope"
require "user.toggleterm"
require "user.treesitter"
require "user.which-key"

require "user.mason"
require "user.lsp"

